parserOptions:
  ecmaVersion: 10
  sourceType: module
env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier:
    - error
    - singleQuote: true